module.exports = {
     consequence: ("../dictModels/consequenceModel")
    const Effort = require ("../dictModels/effortModel")
    const Reason = require("../reasonModel")
    const Repayment = require("../repaymentModel")
    const Event = require("../eventModel")
    const User = require("../userModel")
// const EventStateModel = require("../eventStateModel")
    const BusinessLine = require("../dictModels/businessLine")
    const Client = require("../dictModels/client")
    const ConsequenceType = require("../dictModels/consequenceType")
    const Cpr = require("../dictModels/cpr")
    const Currency = require("../dictModels/currency")
    const DefenceLine = require("../dictModels/defenceLine")
    const FunctBlock = require("../dictModels/functBlock")
    const OrgStructure = require("../dictModels/functBlock")
    const OtherRisk = require("../dictModels/otherRisk")
    const Process = require("../dictModels/process")
    const ReasonType = require("../dictModels/reasonType")
    const RepaymentType = require("../dictModels/repaymentType")
    const RepaymentTypeGroup = require("../dictModels/repaymentTypeGroup")
    const Researcher = require("../dictModels/researcher")
    const RiskType = require("../dictModels/riskType")
    const SourceType = require("../dictModels/sourceType")
    const Status = require("../dictModels/status")

}